project:
  type: website

website:
  title: "My Portfolio"

  sidebar:
    style: docked
    search: true
    logo: profile.jpg

    tools:
      - icon: linkedin
        href: https://linkedin.com/in/manasvi-vardham
        target: _blank

      - icon: github
        href: https://github.com/mvardham
        target: _blank

      - icon: envelope
        href: mailto:mvardham@uci.edu

    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: Resume.pdf

format:
  html:
    theme: cosmo
    page-layout: full
    css: styles.css